[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
categories = ["algorithms", "science"]
description = """
Genetic algorithms library. Supports linear genetic programming
and evolution of GA hyper parameters.
"""
edition = "2021"
keywords = [
  "genetic",
  "ga",
  "evolutionary",
  "algorithm",
  "linear",
  "programming",
]
license = "MIT OR Apache-2.0"
name = "memega"
repository = "https://github.com/Edgeworth/memega"
version = "0.1.0"

[workspace]
members = ["memega-examples"]

[dependencies]
approx = "0.5.1"
concurrent_lru = "0.2.0"
derive_more = "0.99.17"
enumset = "1.0.10"
eyre = "0.6.8"
float-pretty-print = "0.1.1"
num-traits = "0.2.14"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.1"
smallvec = "1.8.0"
strum = "0.24.0"
strum_macros = "0.24.0"
