[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
categories = ["algorithms", "science"]
description = "genetic algorithm library"
edition = "2021"
keywords = ["genetic", "ga", "evolutionary", "algorithm"]
license = "MIT OR Apache-2.0"
name = "memega"
repository = "https://github.com/Edgeworth/memega"
version = "0.1.0"

[dependencies]
approx = "0.5.1"
color-eyre = "0.6.1"
concurrent_lru = "0.2.0"
derive_more = "0.99.17"
enumset = "*"
eyre = "0.6.7"
float-pretty-print = "0.1.1"
log = "0.4.16"
memestat = {version = "0.1.0", git = "https://github.com/Edgeworth/memestat"}
num-traits = "0.2.14"
num_enum = "0.5.7"
pretty_env_logger = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.1"
smallvec = "1.8.0"
strum = "0.24.0"
strum_macros = "0.24.0"

[dev-dependencies]
criterion = {version = "0.3.5", features = ["real_blackbox"]}
plotters = "0.3.1"

[[bench]]
harness = false
name = "examples"

# Build dependencies with optimisations - debug builds will run faster
# but dependencies don't change often.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
