[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "memega"
version = "0.1.0"

[dependencies]
approx = "*"
color-eyre = "*"
concurrent_lru = "*"
derive_more = "*"
eyre = "*"
float-pretty-print = "*"
log = "*"
memestat = {path = "../memestat"}
num-traits = "*"
num_enum = "*"
plotters = "*"
pretty_env_logger = "*"
rand = "*"
rand_distr = "*"
rayon = "*"
smallvec = "*"
strum = "*"
strum_macros = "*"

[dev-dependencies]
criterion = {version = "*", features = ["real_blackbox"]}

[[bench]]
harness = false
name = "examples"
