[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
categories = ["algorithms", "science"]
description = "memega examples"
edition = "2021"
keywords = ["genetic", "ga", "evolutionary", "algorithm"]
license = "MIT OR Apache-2.0"
name = "memega-examples"
repository = "https://github.com/Edgeworth/memega"
version = "0.1.0"

[dependencies]
approx = "0.5.1"
clap = {version = "3.2.23", features = ["derive", "unicode", "wrap_help"]}
color-eyre = "0.6.2"
derive_more = "0.99.17"
enumset = "1.0.12"
eyre = "0.6.8"
log = "0.4.17"
memega = {version = "0.1.0", path = ".."}
num-traits = "0.2.15"
pretty_env_logger = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.3"
savage_core = "0.2.0"
smallvec = "1.10.0"
strum = "0.24.1"
strum_macros = "0.24.3"
textwrap = "0.15.2"

[dev-dependencies]
criterion = {version = "0.4.0", features = ["real_blackbox"]}

[[bench]]
harness = false
name = "examples"
